{% set name = "pybboxes" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybboxes-{{ version }}.tar.gz
  sha256: f34bcdff25aa05abbd501430cf25f42d9635c49727145671ac96b6d10e2c1faf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6

test:
  imports:
    - pybboxes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/devrimcavusoglu/pybboxes
  summary: Light Weight Toolkit for Bounding Boxes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - devrimcavusoglu
    - fcakyon
